language: node_js
node_js:
  - '6'
before_install:
  - nvm install 6.9.1
  - cd ./generator-utils
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
  - npm install
script: npm test
branches:
  only:
    - master